import { Snapshot, TraceEntry } from './machine'
import { SIG } from './signals'

export type LedColor = 'red' | 'yellow' | 'green' | 'blue'

export interface LedBarDef {
  label: string
  color: LedColor
  count: number
  seriesOhm: number
  value: (s: Snapshot) => number
}

export interface PinSignal {
  label: string
  sample: (t: TraceEntry) => number
}

export interface ChipDef {
  ref: string
  part: string
  pins?: Record<string, string>
  signals?: Record<string, PinSignal>
}

export type PassiveKind = 'res' | 'cap' | 'rnet' | 'pot' | 'led' | 'switch' | 'ledbar'

export interface PassiveDef {
  ref: string
  kind: PassiveKind
  value: string
  color?: string
  pins?: Record<string, string>
  hidden3d?: boolean
}

export interface ModuleDef {
  id: string
  name: string
  position: [number, number]
  size: [number, number]
  chips: ChipDef[]
  passives: PassiveDef[]
  leds: LedBarDef[]
  sevenSeg?: boolean
  description: string
}

const bit = (label: string, sel: (t: TraceEntry) => number, n: number): PinSignal => ({
  label: `${label}${n}`,
  sample: (t) => (sel(t) >> n) & 1,
})

const sig = (name: keyof typeof SIG): PinSignal => ({
  label: name,
  sample: (t) => ((t.controlWord & SIG[name]) !== 0 ? 1 : 0),
})

const busPins = (side: 'A' | 'B', label: string, sel: (t: TraceEntry) => number): Record<string, PinSignal> => {
  const pins: Record<string, PinSignal> = {}
  for (let i = 0; i < 8; i++) {
    const pin = side === 'A' ? String(2 + i) : String(18 - i)
    pins[pin] = bit(side === 'B' ? 'BUS' : label, side === 'B' ? (t) => t.bus : sel, i)
  }
  return pins
}

const regQ = (label: string, sel: (t: TraceEntry) => number, base: number): Record<string, PinSignal> => ({
  '3': bit(label, sel, base),
  '4': bit(label, sel, base + 1),
  '5': bit(label, sel, base + 2),
  '6': bit(label, sel, base + 3),
})

const bar8 = (prefix: string): Record<string, string> => {
  const pins: Record<string, string> = {}
  for (let i = 0; i < 8; i++) pins[String(i + 1)] = `${prefix}${i}`
  return pins
}

const rnet9 = (prefix: string): Record<string, string> => {
  const pins: Record<string, string> = { '1': 'GND' }
  for (let i = 0; i < 8; i++) pins[String(i + 2)] = `${prefix}${i}`
  return pins
}

const spgNet = (n: number): string => (n < 8 ? `SP${n}` : 'VCC')
const xNet = (n: number): string => (n < 8 ? `X${n}` : 'GND')

const muxChip = (index: number): ChipDef => {
  const n = index * 2
  const pins: Record<string, string> = {
    '1': 'GND', '15': 'GND', '14': 'CW14', '2': 'CW15',
    '6': `PC${n}`, '5': `TMP${n}`, '4': spgNet(n), '3': `TX${n}`, '7': `MAR${n}`,
  }
  const signals: Record<string, PinSignal> = { '7': bit('MAR', (t) => t.mar, n) }
  if (n + 1 <= 12) {
    Object.assign(pins, { '10': `PC${n + 1}`, '11': `TMP${n + 1}`, '12': spgNet(n + 1), '13': `TX${n + 1}`, '9': `MAR${n + 1}` })
    signals['9'] = bit('MAR', (t) => t.mar, n + 1)
  } else {
    Object.assign(pins, { '10': 'GND', '11': 'GND', '12': 'GND', '13': 'GND', '9': 'NC' })
  }
  return { ref: `U${70 + index}`, part: '74HC153', pins, signals }
}

const adderChip = (index: number): ChipDef => {
  const m = index * 4
  return {
    ref: `U${77 + index}`,
    part: '74HC283',
    pins: {
      '5': `TMP${m}`, '6': xNet(m), '4': `TX${m}`,
      '3': `TMP${m + 1}`, '2': xNet(m + 1), '1': `TX${m + 1}`,
      '14': `TMP${m + 2}`, '15': xNet(m + 2), '13': `TX${m + 2}`,
      '12': `TMP${m + 3}`, '11': xNet(m + 3), '10': `TX${m + 3}`,
      '7': index === 0 ? 'GND' : `TXC${index}`,
      '9': index === 3 ? 'NC' : `TXC${index + 1}`,
    },
  }
}

export const MODULES: ModuleDef[] = [
  {
    id: 'clock',
    name: 'CLOCK',
    position: [-3.2, -4.9],
    size: [2.7, 1.7],
    description: '555 astable with run/step switches, plus the power-on-reset RC and reset button driving RES~',
    chips: [
      { ref: 'U1', part: 'LM555', pins: { '2': '555_THR', '3': '555_OUT', '5': '555_CV', '6': '555_THR', '7': '555_DIS' } },
      { ref: 'U2', part: '74HC14', signals: { '2': { label: 'CLK', sample: (t) => t.cycle & 1 } } },
    ],
    passives: [
      { ref: 'R1', kind: 'pot', value: '1M', pins: { '1': '555_DIS', '2': '555_THR', '3': 'NC' } },
      { ref: 'R2', kind: 'res', value: '1K', pins: { '1': 'VCC', '2': '555_DIS' } },
      { ref: 'C1', kind: 'cap', value: '10nF', pins: { '1': '555_THR', '2': 'GND' } },
      { ref: 'SW1', kind: 'switch', value: 'step', pins: { '1': 'SW1_DEB', '2': 'GND' } },
      { ref: 'SW2', kind: 'switch', value: 'mode', pins: { '1': 'SW2_DEB', '2': 'GND' } },
      { ref: 'R4', kind: 'res', value: '470', pins: { '1': 'CLK', '2': 'D1A' } },
      { ref: 'D1', kind: 'led', value: 'clk', color: '#4c8dff', hidden3d: true, pins: { '1': 'D1A', '2': 'GND' } },
      { ref: 'R3', kind: 'res', value: '10K', pins: { '1': 'VCC', '2': 'RES_RC' } },
      { ref: 'C2', kind: 'cap', value: '10uF', pins: { '1': 'RES_RC', '2': 'GND' } },
      { ref: 'SW4', kind: 'switch', value: 'reset', pins: { '1': 'RES_RC', '2': 'GND' } },
    ],
    leds: [{ label: 'CLK', color: 'blue', count: 1, seriesOhm: 470, value: (s) => (s.halted ? 0 : s.cycle & 1) }],
  },
  {
    id: 'pc',
    name: 'PROGRAM COUNTER 13B',
    position: [3.2, -4.9],
    size: [2.7, 1.8],
    description: 'Four cascaded 74HC161 counters form the 13-bit PC (A0-A12 drive the full 6264)',
    chips: [
      { ref: 'U5', part: '74HC161', signals: { '14': bit('PC', (t) => t.pc, 0), '13': bit('PC', (t) => t.pc, 1), '12': bit('PC', (t) => t.pc, 2), '11': bit('PC', (t) => t.pc, 3) } },
      { ref: 'U6', part: '74HC161', signals: { '14': bit('PC', (t) => t.pc, 4), '13': bit('PC', (t) => t.pc, 5), '12': bit('PC', (t) => t.pc, 6), '11': bit('PC', (t) => t.pc, 7) } },
      { ref: 'U7', part: '74HC161', signals: { '14': bit('PC', (t) => t.pc, 8), '13': bit('PC', (t) => t.pc, 9), '12': bit('PC', (t) => t.pc, 10), '11': bit('PC', (t) => t.pc, 11) } },
      { ref: 'U9', part: '74HC161', signals: { '14': bit('PC', (t) => t.pc, 12) } },
      { ref: 'U8', part: '74HC245', signals: { ...busPins('A', 'PC', (t) => t.pc), ...busPins('B', 'PC', (t) => t.pc) } },
      { ref: 'U19', part: '74HC245' },
    ],
    passives: [
      { ref: 'RN1', kind: 'rnet', value: '470x9', pins: rnet9('PC') },
      { ref: 'LB1', kind: 'ledbar', value: 'PC LO', color: '#34c759', hidden3d: true, pins: bar8('PC') },
      { ref: 'RN7', kind: 'rnet', value: '470x6', pins: { '1': 'GND', '2': 'PC8', '3': 'PC9', '4': 'PC10', '5': 'PC11', '6': 'PC12' } },
      { ref: 'LB7', kind: 'ledbar', value: 'PC HI', color: '#34c759', hidden3d: true, pins: { '1': 'PC8', '2': 'PC9', '3': 'PC10', '4': 'PC11', '5': 'PC12' } },
    ],
    leds: [
      { label: 'PCH', color: 'green', count: 5, seriesOhm: 470, value: (s) => s.pc >> 8 },
      { label: 'PC', color: 'green', count: 8, seriesOhm: 470, value: (s) => s.pc & 0xff },
    ],
  },
  {
    id: 'regs',
    name: 'A / X REGISTERS',
    position: [3.2, -2.9],
    size: [2.7, 1.9],
    description: 'A in 74HC173 latches; X in 74HC193 up/down counters (INX/DEX/TXS), bus transceivers',
    chips: [
      { ref: 'U10', part: '74HC173', signals: regQ('A', (t) => t.a, 0) },
      { ref: 'U11', part: '74HC173', signals: regQ('A', (t) => t.a, 4) },
      { ref: 'U12', part: '74HC193', signals: regQ('X', (t) => t.b, 0) },
      { ref: 'U13', part: '74HC193', signals: regQ('X', (t) => t.b, 4) },
      { ref: 'U14', part: '74HC245', signals: busPins('B', 'BUS', (t) => t.bus) },
      { ref: 'U15', part: '74HC245' },
    ],
    passives: [
      { ref: 'RN2', kind: 'rnet', value: '220x9', pins: rnet9('A') },
      { ref: 'RN3', kind: 'rnet', value: '220x9', pins: rnet9('X') },
      { ref: 'LB2', kind: 'ledbar', value: 'A', color: '#ff453a', hidden3d: true, pins: bar8('A') },
      { ref: 'LB3', kind: 'ledbar', value: 'X', color: '#ff453a', hidden3d: true, pins: bar8('X') },
    ],
    leds: [
      { label: 'A', color: 'red', count: 8, seriesOhm: 220, value: (s) => s.a },
      { label: 'X', color: 'red', count: 8, seriesOhm: 220, value: (s) => s.x },
    ],
  },
  {
    id: 'sp',
    name: 'STACK POINTER',
    position: [3.2, -0.9],
    size: [2.7, 1.4],
    description: '74HC193 up/down counters - push decrements, pop increments, stack lives at 0x1Fxx',
    chips: [
      { ref: 'U16', part: '74HC193' },
      { ref: 'U17', part: '74HC193' },
      { ref: 'U18', part: '74HC245', signals: busPins('B', 'BUS', (t) => t.bus) },
    ],
    passives: [
      { ref: 'RN4', kind: 'rnet', value: '220x9', pins: rnet9('SP') },
      { ref: 'LB4', kind: 'ledbar', value: 'SP', color: '#ffd60a', hidden3d: true, pins: bar8('SP') },
    ],
    leds: [{ label: 'SP', color: 'yellow', count: 8, seriesOhm: 220, value: (s) => s.sp }],
  },
  {
    id: 'alu',
    name: 'ALU 74HC181',
    position: [3.2, 0.7],
    size: [2.7, 1.9],
    description: 'Two 74HC181 slices with the hidden B operand register, shift-right mux, and the flags register',
    chips: [
      { ref: 'U20', part: '74HC181' },
      { ref: 'U21', part: '74HC181' },
      { ref: 'U24', part: '74HC173' },
      { ref: 'U25', part: '74HC173' },
      { ref: 'U26', part: '74HC157' },
      { ref: 'U27', part: '74HC157' },
      { ref: 'U28', part: '74HC157' },
      { ref: 'U29', part: '74HC157' },
      { ref: 'U22', part: '74HC245', signals: busPins('B', 'BUS', (t) => t.bus) },
      {
        ref: 'U23',
        part: '74HC173',
        signals: {
          '3': { label: 'CF', sample: (t) => (t.carry ? 1 : 0) },
          '4': { label: 'ZF', sample: (t) => (t.zero ? 1 : 0) },
          '5': { label: 'IEN', sample: (t) => ((t.controlWord & SIG.IEN) !== 0 ? 1 : 0) },
        },
      },
    ],
    passives: [
      { ref: 'RN9', kind: 'rnet', value: '470x5', pins: { '1': 'GND', '2': 'FC', '3': 'FZ', '4': 'FN', '5': 'FIE' } },
      { ref: 'LB9', kind: 'ledbar', value: 'FLAGS', color: '#ff453a', hidden3d: true, pins: { '1': 'FC', '2': 'FZ', '3': 'FN', '4': 'FIE' } },
      { ref: 'R18', kind: 'res', value: '470', pins: { '1': 'CF', '2': 'GND' } },
      { ref: 'R19', kind: 'res', value: '470', pins: { '1': 'ZF', '2': 'GND' } },
    ],
    leds: [
      {
        label: 'FLAGS',
        color: 'green',
        count: 4,
        seriesOhm: 470,
        value: (s) => (s.carry ? 1 : 0) | (s.zero ? 2 : 0) | (s.negative ? 4 : 0) | (s.interruptsEnabled ? 8 : 0),
      },
    ],
  },
  {
    id: 'ram',
    name: 'RAM 8KB',
    position: [-3.2, -2.7],
    size: [2.8, 2.0],
    description: '28C64 MOS ROM at 0x0000-0x0FFF, 6264 SRAM above it; A12 decode via the 138, 13-bit MAR',
    chips: [
      { ref: 'U30', part: '74HC173', signals: regQ('MAR', (t) => t.mar, 0) },
      { ref: 'U31', part: '74HC173', signals: regQ('MAR', (t) => t.mar, 4) },
      { ref: 'U32', part: '74HC173', signals: { '3': bit('MAR', (t) => t.mar, 8), '4': bit('MAR', (t) => t.mar, 9), '5': bit('MAR', (t) => t.mar, 10), '6': bit('MAR', (t) => t.mar, 11) } },
      { ref: 'U35', part: '74HC173', signals: { '3': bit('MAR', (t) => t.mar, 12) } },
      { ref: 'U33', part: 'HM6264', signals: { '20': sig('MEMR'), '27': sig('MEMW') } },
      { ref: 'U36', part: 'AT28C64' },
      { ref: 'U37', part: '74HC138' },
      { ref: 'U34', part: '74HC245', signals: busPins('B', 'BUS', (t) => t.bus) },
    ],
    passives: [
      { ref: 'RN5', kind: 'rnet', value: '220x9', pins: rnet9('MAR') },
      { ref: 'LB5', kind: 'ledbar', value: 'ADDR', color: '#ffd60a', hidden3d: true, pins: bar8('MAR') },
      { ref: 'RN8', kind: 'rnet', value: '220x6', pins: { '1': 'GND', '2': 'MAR8', '3': 'MAR9', '4': 'MAR10', '5': 'MAR11', '6': 'MAR12' } },
      { ref: 'LB8', kind: 'ledbar', value: 'ADDR HI', color: '#ffd60a', hidden3d: true, pins: { '1': 'MAR8', '2': 'MAR9', '3': 'MAR10', '4': 'MAR11', '5': 'MAR12' } },
    ],
    leds: [
      { label: 'MARH', color: 'yellow', count: 5, seriesOhm: 220, value: (s) => s.mar >> 8 },
      { label: 'ADDR', color: 'yellow', count: 8, seriesOhm: 220, value: (s) => s.mar & 0xff },
    ],
  },
  {
    id: 'control',
    name: 'CONTROL 4x28C256',
    position: [-3.2, -0.4],
    size: [2.8, 1.9],
    description: 'Four 28C256 ROMs addressed by flags(3)|opcode(8)|step(4); NAND strobe gating, 138 field decoders, 28C16 ALU-function decode',
    chips: [
      { ref: 'U40', part: '74HC273', signals: { '2': bit('OPC', (t) => t.opcode, 0), '5': bit('OPC', (t) => t.opcode, 1), '6': bit('OPC', (t) => t.opcode, 2), '9': bit('OPC', (t) => t.opcode, 3) } },
      { ref: 'U41', part: 'AT28C256' },
      { ref: 'U42', part: 'AT28C256' },
      { ref: 'U43', part: 'AT28C256' },
      { ref: 'U44', part: 'AT28C256' },
      { ref: 'U45', part: '74HC161', signals: { '14': bit('STEP', (t) => t.step, 0), '13': bit('STEP', (t) => t.step, 1), '12': bit('STEP', (t) => t.step, 2), '11': bit('STEP', (t) => t.step, 3) } },
      { ref: 'U46', part: '74HC138' },
      { ref: 'U58', part: '74HC138' },
      { ref: 'U66', part: '74HC00' },
      { ref: 'U67', part: '74HC00' },
      { ref: 'U68', part: '74HC00' },
      { ref: 'U69', part: '74HC138' },
      { ref: 'U90', part: '74HC138' },
      { ref: 'U91', part: 'AT28C16' },
      { ref: 'U47', part: '74HC161' },
      { ref: 'U48', part: '74HC161' },
      { ref: 'U49', part: '74HC161' },
      { ref: 'U59', part: '74HC161' },
    ],
    passives: [
      { ref: 'RN6', kind: 'rnet', value: '470x9', pins: rnet9('OP') },
      { ref: 'LB6', kind: 'ledbar', value: 'OPC', color: '#4c8dff', hidden3d: true, pins: bar8('OP') },
    ],
    leds: [{ label: 'OPC', color: 'blue', count: 8, seriesOhm: 470, value: (s) => s.irOpcode }],
  },
  {
    id: 'io',
    name: 'TERMINAL + DISK IO',
    position: [-3.2, 1.5],
    size: [2.8, 1.9],
    description: 'ACIA console with TX/RX status bits, port decode, SD disk with ready bit, and the 16-bit timer (161 counters + 688 comparator vs the period latch)',
    chips: [
      { ref: 'U50', part: 'MC6850', signals: { '2': sig('IOR'), '3': sig('IOW') } },
      { ref: 'U55', part: '74HC273' },
      { ref: 'U56', part: '74HC161' },
      { ref: 'U57', part: '74HC161' },
      { ref: 'U63', part: '74HC161' },
      { ref: 'U64', part: '74HC161' },
      { ref: 'U65', part: '74HC688' },
      { ref: 'U51', part: '74HC138' },
      { ref: 'U52', part: '74HC595' },
      { ref: 'U53', part: '74HC165' },
      { ref: 'U54', part: '74HC245', signals: busPins('B', 'BUS', (t) => t.bus) },
    ],
    passives: [
      { ref: 'C10', kind: 'cap', value: '100nF', pins: { '1': 'VCC', '2': 'GND' } },
      { ref: 'D10', kind: 'led', value: 'rx', color: '#34c759', hidden3d: true, pins: { '1': 'IOR', '2': 'GND' } },
      { ref: 'D11', kind: 'led', value: 'tx', color: '#ff453a', hidden3d: true, pins: { '1': 'IOW', '2': 'GND' } },
    ],
    leds: [
      {
        label: 'IO',
        color: 'green',
        count: 2,
        seriesOhm: 470,
        value: (s) => ((s.controlWord & SIG.IOR) !== 0 ? 1 : 0) | ((s.controlWord & SIG.IOW) !== 0 ? 2 : 0),
      },
    ],
  },
  {
    id: 'output',
    name: 'DISPLAY',
    position: [3.2, 2.8],
    size: [2.7, 1.9],
    description: 'The MSAP-1 multiplexed 7-segment display, now a memory-mapped port',
    chips: [
      { ref: 'U60', part: '74HC273', signals: { '2': bit('OUT', (t) => t.out, 0) } },
      { ref: 'U61', part: 'LM555' },
      { ref: 'U62', part: 'AT28C16' },
    ],
    passives: [{ ref: 'RN10', kind: 'rnet', value: '220x9', pins: { '1': 'GND', '2': 'SEG_A', '3': 'SEG_B', '4': 'SEG_C', '5': 'SEG_D', '6': 'SEG_E', '7': 'SEG_F', '8': 'SEG_G', '9': 'SEG_DP' } }],
    leds: [],
    sevenSeg: true,
  },
  {
    id: 'addr',
    name: 'ADDRESS PATH',
    position: [-3.2, 3.3],
    size: [2.8, 1.7],
    description: 'MAR source mux (PC / TMP / stack page / TMP+X) from seven 74HC153 plus the four-chip index adder',
    chips: [
      muxChip(0), muxChip(1), muxChip(2), muxChip(3), muxChip(4), muxChip(5), muxChip(6),
      adderChip(0), adderChip(1), adderChip(2), adderChip(3),
    ],
    passives: [],
    leds: [],
  },
  {
    id: 'bus',
    name: 'BUS',
    position: [0, -1.0],
    size: [0.95, 8.0],
    description: '8-bit data bus with 11-bit address sidecar',
    chips: [],
    passives: [
      { ref: 'RN13', kind: 'rnet', value: '220x9', pins: rnet9('BUS') },
      { ref: 'LB12', kind: 'ledbar', value: 'BUS', color: '#ffd60a', hidden3d: true, pins: bar8('BUS') },
    ],
    leds: [{ label: 'BUS', color: 'yellow', count: 8, seriesOhm: 220, value: (s) => s.bus }],
  },
]

export interface ConnectionDef {
  from: string
  to: string
  kind: 'bus' | 'ctl' | 'clk'
  activeMask?: number
}


const BASE_PINS: Record<string, Record<string, string>> = {
  'U2': {
    '1': '555_OUT',
    '2': 'CLK',
    '3': 'RES_RC',
    '4': 'RESP',
    '5': 'RESP',
    '6': 'RES~',
    '9': 'CLK',
    '8': 'CLKG'
  },
  'U5': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'PCLD~',
    '7': 'PCI',
    '10': 'PCI',
    '15': 'PCC1',
    '3': 'TMP0',
    '4': 'TMP1',
    '5': 'TMP2',
    '6': 'TMP3',
    '14': 'PC0',
    '13': 'PC1',
    '12': 'PC2',
    '11': 'PC3'
  },
  'U6': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'PCLD~',
    '7': 'PCC1',
    '10': 'PCC1',
    '15': 'PCC2',
    '3': 'TMP4',
    '4': 'TMP5',
    '5': 'TMP6',
    '6': 'TMP7',
    '14': 'PC4',
    '13': 'PC5',
    '12': 'PC6',
    '11': 'PC7'
  },
  'U7': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'PCLD~',
    '7': 'PCC2',
    '10': 'PCC2',
    '15': 'PCC3',
    '3': 'TMP8',
    '4': 'TMP9',
    '5': 'TMP10',
    '6': 'TMP11',
    '14': 'PC8',
    '13': 'PC9',
    '12': 'PC10',
    '11': 'PC11'
  },
  'U9': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'PCLD~',
    '7': 'PCC3',
    '10': 'PCC3',
    '15': 'NC',
    '3': 'TMP12',
    '4': 'GND',
    '5': 'GND',
    '6': 'GND',
    '14': 'PC12',
    '13': 'NC',
    '12': 'NC',
    '11': 'NC'
  },
  'U8': {
    '1': 'VCC',
    '19': 'PCLO~',
    '2': 'PC0',
    '3': 'PC1',
    '4': 'PC2',
    '5': 'PC3',
    '6': 'PC4',
    '7': 'PC5',
    '8': 'PC6',
    '9': 'PC7',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7'
  },
  'U19': {
    '1': 'VCC',
    '19': 'PCHO~',
    '2': 'PC8',
    '3': 'PC9',
    '4': 'PC10',
    '5': 'PC11',
    '6': 'PC12',
    '7': 'GND',
    '8': 'GND',
    '9': 'GND',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'NC',
    '12': 'NC',
    '11': 'NC'
  },
  'U10': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'AI~',
    '10': 'AI~',
    '14': 'BUS0',
    '13': 'BUS1',
    '12': 'BUS2',
    '11': 'BUS3',
    '3': 'A0',
    '4': 'A1',
    '5': 'A2',
    '6': 'A3'
  },
  'U11': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'AI~',
    '10': 'AI~',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7',
    '3': 'A4',
    '4': 'A5',
    '5': 'A6',
    '6': 'A7'
  },
  'U12': {
    '15': 'BUS0',
    '1': 'BUS1',
    '10': 'BUS2',
    '9': 'BUS3',
    '3': 'X0',
    '2': 'X1',
    '6': 'X2',
    '7': 'X3',
    '5': 'XU',
    '4': 'XD',
    '11': 'XLD~',
    '14': 'GND',
    '12': 'XCU',
    '13': 'XCB'
  },
  'U13': {
    '15': 'BUS4',
    '1': 'BUS5',
    '10': 'BUS6',
    '9': 'BUS7',
    '3': 'X4',
    '2': 'X5',
    '6': 'X6',
    '7': 'X7',
    '5': 'XCU',
    '4': 'XCB',
    '11': 'XLD~',
    '14': 'GND',
    '12': 'NC',
    '13': 'NC'
  },
  'U14': {
    '1': 'VCC',
    '19': 'AO~',
    '2': 'A0',
    '3': 'A1',
    '4': 'A2',
    '5': 'A3',
    '6': 'A4',
    '7': 'A5',
    '8': 'A6',
    '9': 'A7',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7'
  },
  'U15': {
    '1': 'VCC',
    '19': 'XO~',
    '2': 'X0',
    '3': 'X1',
    '4': 'X2',
    '5': 'X3',
    '6': 'X4',
    '7': 'X5',
    '8': 'X6',
    '9': 'X7',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7'
  },
  'U16': {
    '15': 'BUS0',
    '1': 'BUS1',
    '10': 'BUS2',
    '9': 'BUS3',
    '3': 'SP0',
    '2': 'SP1',
    '6': 'SP2',
    '7': 'SP3',
    '5': 'SPU',
    '4': 'SPDN',
    '11': 'SPL~',
    '14': 'GND',
    '12': 'SPCU',
    '13': 'SPCB'
  },
  'U17': {
    '15': 'BUS4',
    '1': 'BUS5',
    '10': 'BUS6',
    '9': 'BUS7',
    '3': 'SP4',
    '2': 'SP5',
    '6': 'SP6',
    '7': 'SP7',
    '5': 'SPCU',
    '4': 'SPCB',
    '11': 'SPL~',
    '14': 'GND',
    '12': 'NC',
    '13': 'NC'
  },
  'U18': {
    '1': 'VCC',
    '19': 'VCC',
    '2': 'SP0',
    '3': 'SP1',
    '4': 'SP2',
    '5': 'SP3',
    '6': 'SP4',
    '7': 'SP5',
    '8': 'SP6',
    '9': 'SP7',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7'
  },
  'U24': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'BI~',
    '10': 'BI~',
    '14': 'BUS0',
    '13': 'BUS1',
    '12': 'BUS2',
    '11': 'BUS3',
    '3': 'B0',
    '4': 'B1',
    '5': 'B2',
    '6': 'B3'
  },
  'U25': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'BI~',
    '10': 'BI~',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7',
    '3': 'B4',
    '4': 'B5',
    '5': 'B6',
    '6': 'B7'
  },
  'U28': {
    '1': 'AXS',
    '15': 'GND',
    '2': 'A0',
    '3': 'X0',
    '4': 'AS0',
    '5': 'A1',
    '6': 'X1',
    '7': 'AS1',
    '14': 'A2',
    '13': 'X2',
    '12': 'AS2',
    '11': 'A3',
    '10': 'X3',
    '9': 'AS3'
  },
  'U29': {
    '1': 'AXS',
    '15': 'GND',
    '2': 'A4',
    '3': 'X4',
    '4': 'AS4',
    '5': 'A5',
    '6': 'X5',
    '7': 'AS5',
    '14': 'A6',
    '13': 'X6',
    '12': 'AS6',
    '11': 'A7',
    '10': 'X7',
    '9': 'AS7'
  },
  'U20': {
    '2': 'AS0',
    '23': 'AS1',
    '21': 'AS2',
    '19': 'AS3',
    '1': 'B0',
    '22': 'B1',
    '20': 'B2',
    '18': 'B3',
    '9': 'ALF0',
    '10': 'ALF1',
    '11': 'ALF2',
    '13': 'ALF3',
    '6': 'ALS0',
    '5': 'ALS1',
    '4': 'ALS2',
    '3': 'ALS3',
    '8': 'ALM',
    '7': 'ALC',
    '16': 'ALC4'
  },
  'U21': {
    '2': 'AS4',
    '23': 'AS5',
    '21': 'AS6',
    '19': 'AS7',
    '1': 'B4',
    '22': 'B5',
    '20': 'B6',
    '18': 'B7',
    '9': 'ALF4',
    '10': 'ALF5',
    '11': 'ALF6',
    '13': 'ALF7',
    '6': 'ALS0',
    '5': 'ALS1',
    '4': 'ALS2',
    '3': 'ALS3',
    '8': 'ALM',
    '7': 'ALC4',
    '16': 'ALCO'
  },
  'U26': {
    '1': 'ALSHR',
    '15': 'GND',
    '2': 'ALF0',
    '3': 'ALF1',
    '4': 'ALO0',
    '5': 'ALF1',
    '6': 'ALF2',
    '7': 'ALO1',
    '14': 'ALF2',
    '13': 'ALF3',
    '12': 'ALO2',
    '11': 'ALF3',
    '10': 'ALF4',
    '9': 'ALO3'
  },
  'U27': {
    '1': 'ALSHR',
    '15': 'GND',
    '2': 'ALF4',
    '3': 'ALF5',
    '4': 'ALO4',
    '5': 'ALF5',
    '6': 'ALF6',
    '7': 'ALO5',
    '14': 'ALF6',
    '13': 'ALF7',
    '12': 'ALO6',
    '11': 'ALF7',
    '10': 'GND',
    '9': 'ALO7'
  },
  'U22': {
    '1': 'VCC',
    '19': 'EO~',
    '2': 'ALO0',
    '3': 'ALO1',
    '4': 'ALO2',
    '5': 'ALO3',
    '6': 'ALO4',
    '7': 'ALO5',
    '8': 'ALO6',
    '9': 'ALO7',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7'
  },
  'U23': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'FI~',
    '10': 'FI~',
    '14': 'ALCO',
    '13': 'FZD',
    '12': 'ALF7',
    '11': 'IED',
    '3': 'FC',
    '4': 'FZ',
    '5': 'FN',
    '6': 'FIE'
  },
  'U30': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'MI~',
    '10': 'MI~',
    '14': 'MARD0',
    '13': 'MARD1',
    '12': 'MARD2',
    '11': 'MARD3',
    '3': 'MAR0',
    '4': 'MAR1',
    '5': 'MAR2',
    '6': 'MAR3'
  },
  'U31': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'MI~',
    '10': 'MI~',
    '14': 'MARD4',
    '13': 'MARD5',
    '12': 'MARD6',
    '11': 'MARD7',
    '3': 'MAR4',
    '4': 'MAR5',
    '5': 'MAR6',
    '6': 'MAR7'
  },
  'U32': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'MI~',
    '10': 'MI~',
    '14': 'MARD8',
    '13': 'MARD9',
    '12': 'MARD10',
    '11': 'MARD11',
    '3': 'MAR8',
    '4': 'MAR9',
    '5': 'MAR10',
    '6': 'MAR11'
  },
  'U35': {
    '7': 'CLK',
    '15': 'GND',
    '1': 'GND',
    '2': 'GND',
    '9': 'MI~',
    '10': 'MI~',
    '14': 'MARD12',
    '13': 'GND',
    '12': 'GND',
    '11': 'GND',
    '3': 'MAR12',
    '4': 'NC',
    '5': 'NC',
    '6': 'NC'
  },
  'U33': {
    '20': 'RAMCS~',
    '22': 'RO~',
    '27': 'RW~',
    '10': 'MAR0',
    '9': 'MAR1',
    '8': 'MAR2',
    '7': 'MAR3',
    '6': 'MAR4',
    '5': 'MAR5',
    '4': 'MAR6',
    '3': 'MAR7',
    '25': 'MAR8',
    '24': 'MAR9',
    '21': 'MAR10',
    '23': 'MAR11',
    '2': 'MAR12',
    '26': 'GND',
    '1': 'GND',
    '11': 'RD0',
    '12': 'RD1',
    '13': 'RD2',
    '15': 'RD3',
    '16': 'RD4',
    '17': 'RD5',
    '18': 'RD6',
    '19': 'RD7'
  },
  'U36': {
    '20': 'ROMCS~',
    '22': 'RO~',
    '27': 'VCC',
    '10': 'MAR0',
    '9': 'MAR1',
    '8': 'MAR2',
    '7': 'MAR3',
    '6': 'MAR4',
    '5': 'MAR5',
    '4': 'MAR6',
    '3': 'MAR7',
    '25': 'MAR8',
    '24': 'MAR9',
    '21': 'MAR10',
    '23': 'MAR11',
    '2': 'GND',
    '26': 'GND',
    '1': 'GND',
    '11': 'RD0',
    '12': 'RD1',
    '13': 'RD2',
    '15': 'RD3',
    '16': 'RD4',
    '17': 'RD5',
    '18': 'RD6',
    '19': 'RD7'
  },
  'U37': {
    '1': 'MAR12',
    '2': 'GND',
    '3': 'GND',
    '4': 'GND',
    '5': 'GND',
    '6': 'VCC',
    '15': 'ROMCS~',
    '14': 'RAMCS~'
  },
  'U34': {
    '1': 'VCC',
    '19': 'RO~',
    '2': 'RD0',
    '3': 'RD1',
    '4': 'RD2',
    '5': 'RD3',
    '6': 'RD4',
    '7': 'RD5',
    '8': 'RD6',
    '9': 'RD7',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7'
  },
  'U40': {
    '1': 'RES~',
    '11': 'CLK',
    '3': 'BUS0',
    '4': 'BUS1',
    '7': 'BUS2',
    '8': 'BUS3',
    '13': 'BUS4',
    '14': 'BUS5',
    '17': 'BUS6',
    '18': 'BUS7',
    '2': 'OP0',
    '5': 'OP1',
    '6': 'OP2',
    '9': 'OP3',
    '12': 'OP4',
    '15': 'OP5',
    '16': 'OP6',
    '19': 'OP7'
  },
  'U41': {
    '20': 'GND',
    '22': 'GND',
    '27': 'VCC',
    '10': 'STEP0',
    '9': 'STEP1',
    '8': 'STEP2',
    '7': 'STEP3',
    '6': 'OP0',
    '5': 'OP1',
    '4': 'OP2',
    '3': 'OP3',
    '25': 'OP4',
    '24': 'OP5',
    '21': 'OP6',
    '23': 'OP7',
    '2': 'FC',
    '26': 'FZ',
    '1': 'FN',
    '11': 'CW0',
    '12': 'CW1',
    '13': 'CW2',
    '15': 'CW3',
    '16': 'CW4',
    '17': 'CW5',
    '18': 'CW6',
    '19': 'CW7'
  },
  'U42': {
    '20': 'GND',
    '22': 'GND',
    '27': 'VCC',
    '10': 'STEP0',
    '9': 'STEP1',
    '8': 'STEP2',
    '7': 'STEP3',
    '6': 'OP0',
    '5': 'OP1',
    '4': 'OP2',
    '3': 'OP3',
    '25': 'OP4',
    '24': 'OP5',
    '21': 'OP6',
    '23': 'OP7',
    '2': 'FC',
    '26': 'FZ',
    '1': 'FN',
    '11': 'CW8',
    '12': 'CW9',
    '13': 'CW10',
    '15': 'CW11',
    '16': 'CW12',
    '17': 'CW13',
    '18': 'CW14',
    '19': 'CW15'
  },
  'U43': {
    '20': 'GND',
    '22': 'GND',
    '27': 'VCC',
    '10': 'STEP0',
    '9': 'STEP1',
    '8': 'STEP2',
    '7': 'STEP3',
    '6': 'OP0',
    '5': 'OP1',
    '4': 'OP2',
    '3': 'OP3',
    '25': 'OP4',
    '24': 'OP5',
    '21': 'OP6',
    '23': 'OP7',
    '2': 'FC',
    '26': 'FZ',
    '1': 'FN',
    '11': 'CW16',
    '12': 'CW17',
    '13': 'CW18',
    '15': 'CW19',
    '16': 'CW20',
    '17': 'CW21',
    '18': 'CW22',
    '19': 'CW23'
  },
  'U44': {
    '20': 'GND',
    '22': 'GND',
    '27': 'VCC',
    '10': 'STEP0',
    '9': 'STEP1',
    '8': 'STEP2',
    '7': 'STEP3',
    '6': 'OP0',
    '5': 'OP1',
    '4': 'OP2',
    '3': 'OP3',
    '25': 'OP4',
    '24': 'OP5',
    '21': 'OP6',
    '23': 'OP7',
    '2': 'FC',
    '26': 'FZ',
    '1': 'FN',
    '11': 'CW24',
    '12': 'CW25',
    '13': 'CW26',
    '15': 'CW27',
    '16': 'CW28',
    '17': 'CW29',
    '18': 'CW30',
    '19': 'CW31'
  },
  'U45': {
    '1': 'RST~',
    '2': 'CLKG',
    '9': 'VCC',
    '7': 'VCC',
    '10': 'VCC',
    '15': 'NC',
    '3': 'GND',
    '4': 'GND',
    '5': 'GND',
    '6': 'GND',
    '14': 'STEP0',
    '13': 'STEP1',
    '12': 'STEP2',
    '11': 'STEP3'
  },
  'U46': {
    '1': 'CW0',
    '2': 'CW1',
    '3': 'CW2',
    '4': 'CW3',
    '5': 'GND',
    '6': 'VCC',
    '15': 'NC',
    '14': 'RO~',
    '13': 'AO~',
    '12': 'XO~',
    '11': 'BO~',
    '10': 'EO~',
    '9': 'FO~',
    '7': 'PCLO~'
  },
  'U58': {
    '1': 'CW0',
    '2': 'CW1',
    '3': 'CW2',
    '6': 'CW3',
    '4': 'GND',
    '5': 'GND',
    '15': 'PCHO~',
    '14': 'DO~',
    '13': 'VECI~',
    '12': 'VECB~',
    '11': 'ZO~'
  },
  'U47': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'TL~',
    '7': 'TPI',
    '10': 'TPI',
    '15': 'TPC1',
    '3': 'BUS0',
    '4': 'BUS1',
    '5': 'BUS2',
    '6': 'BUS3',
    '14': 'TMP0',
    '13': 'TMP1',
    '12': 'TMP2',
    '11': 'TMP3'
  },
  'U48': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'TL~',
    '7': 'TPC1',
    '10': 'TPC1',
    '15': 'TPC2',
    '3': 'BUS4',
    '4': 'BUS5',
    '5': 'BUS6',
    '6': 'BUS7',
    '14': 'TMP4',
    '13': 'TMP5',
    '12': 'TMP6',
    '11': 'TMP7'
  },
  'U49': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'TH~',
    '7': 'TPC2',
    '10': 'TPC2',
    '15': 'TPC3',
    '3': 'BUS0',
    '4': 'BUS1',
    '5': 'BUS2',
    '6': 'BUS3',
    '14': 'TMP8',
    '13': 'TMP9',
    '12': 'TMP10',
    '11': 'TMP11'
  },
  'U59': {
    '1': 'RES~',
    '2': 'CLK',
    '9': 'TH~',
    '7': 'TPC3',
    '10': 'TPC3',
    '15': 'NC',
    '3': 'BUS4',
    '4': 'BUS5',
    '5': 'BUS6',
    '6': 'BUS7',
    '14': 'TMP12',
    '13': 'TMP13',
    '12': 'TMP14',
    '11': 'TMP15'
  },
  'U55': {
    '1': 'RES~',
    '11': 'IOSEL4~',
    '3': 'BUS0',
    '4': 'BUS1',
    '7': 'BUS2',
    '8': 'BUS3',
    '13': 'BUS4',
    '14': 'BUS5',
    '17': 'BUS6',
    '18': 'BUS7',
    '2': 'TPR0',
    '5': 'TPR1',
    '6': 'TPR2',
    '9': 'TPR3',
    '12': 'TPR4',
    '15': 'TPR5',
    '16': 'TPR6',
    '19': 'TPR7'
  },
  'U56': {
    '1': 'TIRQ~',
    '2': 'CLK',
    '9': 'VCC',
    '7': 'VCC',
    '10': 'VCC',
    '15': 'TCC1',
    '3': 'GND',
    '4': 'GND',
    '5': 'GND',
    '6': 'GND',
    '14': 'TCT0',
    '13': 'TCT1',
    '12': 'TCT2',
    '11': 'TCT3'
  },
  'U57': {
    '1': 'TIRQ~',
    '2': 'CLK',
    '9': 'VCC',
    '7': 'TCC1',
    '10': 'TCC1',
    '15': 'TCC2',
    '3': 'GND',
    '4': 'GND',
    '5': 'GND',
    '6': 'GND',
    '14': 'TCT4',
    '13': 'TCT5',
    '12': 'TCT6',
    '11': 'TCT7'
  },
  'U63': {
    '1': 'TIRQ~',
    '2': 'CLK',
    '9': 'VCC',
    '7': 'TCC2',
    '10': 'TCC2',
    '15': 'TCC3',
    '3': 'GND',
    '4': 'GND',
    '5': 'GND',
    '6': 'GND',
    '14': 'TCT8',
    '13': 'TCT9',
    '12': 'TCT10',
    '11': 'TCT11'
  },
  'U64': {
    '1': 'TIRQ~',
    '2': 'CLK',
    '9': 'VCC',
    '7': 'TCC3',
    '10': 'TCC3',
    '15': 'NC',
    '3': 'GND',
    '4': 'GND',
    '5': 'GND',
    '6': 'GND',
    '14': 'TCT12',
    '13': 'TCT13',
    '12': 'TCT14',
    '11': 'TCT15'
  },
  'U65': {
    '2': 'TCT8',
    '4': 'TCT9',
    '6': 'TCT10',
    '8': 'TCT11',
    '11': 'TCT12',
    '13': 'TCT13',
    '15': 'TCT14',
    '17': 'TCT15',
    '3': 'TPR0',
    '5': 'TPR1',
    '7': 'TPR2',
    '9': 'TPR3',
    '12': 'TPR4',
    '14': 'TPR5',
    '16': 'TPR6',
    '18': 'TPR7',
    '1': 'GND',
    '19': 'TIRQ~'
  },
  'U66': {
    '1': 'CW4',
    '2': 'CLKG',
    '3': 'AI~',
    '4': 'CW6',
    '5': 'CLKG',
    '6': 'BI~',
    '9': 'CW7',
    '10': 'CLKG',
    '8': 'II~',
    '12': 'CW8',
    '13': 'CLKG',
    '11': 'TL~'
  },
  'U67': {
    '1': 'CW9',
    '2': 'CLKG',
    '3': 'TH~',
    '4': 'CW10',
    '5': 'CLKG',
    '6': 'FRI~',
    '9': 'CW11',
    '10': 'CLKG',
    '8': 'RW~',
    '12': 'CW12',
    '13': 'CLKG',
    '11': 'IOW~'
  },
  'U68': {
    '1': 'CW13',
    '2': 'CLKG',
    '3': 'MI~',
    '4': 'CW23',
    '5': 'CLKG',
    '6': 'FI~',
    '9': 'CW5',
    '10': 'CLKG',
    '8': 'XLD~',
    '12': 'CW27',
    '13': 'CLKG',
    '11': 'RST~'
  },
  'U69': {
    '1': 'CW16',
    '2': 'CW17',
    '3': 'CW18',
    '4': 'CW19',
    '5': 'GND',
    '6': 'VCC',
    '14': 'PCI',
    '13': 'PCLD~',
    '12': 'SPU',
    '11': 'SPDN',
    '10': 'SPL~',
    '9': 'TPI',
    '7': 'XU'
  },
  'U90': {
    '1': 'CW16',
    '2': 'CW17',
    '3': 'CW18',
    '6': 'CW19',
    '4': 'GND',
    '5': 'GND',
    '15': 'XD'
  },
  'U91': {
    '8': 'CW20',
    '7': 'CW21',
    '6': 'CW22',
    '5': 'GND',
    '4': 'GND',
    '3': 'GND',
    '2': 'GND',
    '1': 'GND',
    '9': 'ALS0',
    '10': 'ALS1',
    '11': 'ALS2',
    '13': 'ALS3',
    '14': 'ALM',
    '15': 'ALC',
    '16': 'ALSHR',
    '18': 'GND',
    '20': 'GND',
    '21': 'VCC'
  },
  'U50': {
    '22': 'BUS0',
    '21': 'BUS1',
    '20': 'BUS2',
    '19': 'BUS3',
    '18': 'BUS4',
    '17': 'BUS5',
    '16': 'BUS6',
    '15': 'BUS7',
    '8': 'VCC',
    '10': 'IOSEL0~',
    '9': 'GND',
    '11': 'TMP0',
    '13': 'IOW~',
    '14': 'CLK',
    '6': 'TXD',
    '2': 'RXD',
    '7': 'IRQ~'
  },
  'U51': {
    '1': 'TMP0',
    '2': 'TMP1',
    '3': 'TMP2',
    '4': 'GND',
    '5': 'GND',
    '6': 'VCC',
    '15': 'IOSEL0~',
    '14': 'IOSEL1~',
    '13': 'IOSEL2~',
    '12': 'IOSEL3~',
    '11': 'IOSEL4~'
  },
  'U52': {
    '14': 'DSK_OUT',
    '11': 'DSK_SCK',
    '12': 'DSK_LATCH',
    '13': 'GND',
    '10': 'VCC'
  },
  'U53': {
    '10': 'DSK_IN',
    '2': 'DSK_SCK',
    '9': 'DSK_Q',
    '1': 'DSK_LD~',
    '15': 'GND'
  },
  'U54': {
    '1': 'VCC',
    '19': 'DO~',
    '2': 'IOD0',
    '3': 'IOD1',
    '4': 'IOD2',
    '5': 'IOD3',
    '6': 'IOD4',
    '7': 'IOD5',
    '8': 'IOD6',
    '9': 'IOD7',
    '18': 'BUS0',
    '17': 'BUS1',
    '16': 'BUS2',
    '15': 'BUS3',
    '14': 'BUS4',
    '13': 'BUS5',
    '12': 'BUS6',
    '11': 'BUS7'
  },
  'U60': {
    '1': 'RES~',
    '11': 'IOSEL3~',
    '3': 'BUS0',
    '4': 'BUS1',
    '7': 'BUS2',
    '8': 'BUS3',
    '13': 'BUS4',
    '14': 'BUS5',
    '17': 'BUS6',
    '18': 'BUS7',
    '2': 'OUTR0',
    '5': 'OUTR1',
    '6': 'OUTR2',
    '9': 'OUTR3',
    '12': 'OUTR4',
    '15': 'OUTR5',
    '16': 'OUTR6',
    '19': 'OUTR7'
  },
  'U61': {
    '2': 'MUX_THR',
    '3': 'MUX_CLK',
    '6': 'MUX_THR',
    '7': 'MUX_DIS'
  },
  'U62': {
    '8': 'OUTR0',
    '7': 'OUTR1',
    '6': 'OUTR2',
    '5': 'OUTR3',
    '4': 'OUTR4',
    '3': 'OUTR5',
    '2': 'OUTR6',
    '1': 'OUTR7',
    '23': 'DIG0',
    '22': 'DIG1',
    '9': 'SEG_A',
    '10': 'SEG_B',
    '11': 'SEG_C',
    '13': 'SEG_D',
    '14': 'SEG_E',
    '15': 'SEG_F',
    '16': 'SEG_G',
    '17': 'SEG_DP',
    '20': 'GND',
    '18': 'GND'
  }
}

for (const mod of MODULES) {
  for (const chip of mod.chips) {
    const base = BASE_PINS[chip.ref]
    if (base) chip.pins = { ...base, ...chip.pins }
  }
}

export const CONNECTIONS: ConnectionDef[] = [
  { from: 'pc', to: 'bus', kind: 'bus', activeMask: SIG.FETCH },
  { from: 'regs', to: 'bus', kind: 'bus', activeMask: SIG.ALU },
  { from: 'sp', to: 'bus', kind: 'bus', activeMask: SIG.STKR | SIG.STKW },
  { from: 'alu', to: 'bus', kind: 'bus', activeMask: SIG.ALU },
  { from: 'ram', to: 'bus', kind: 'bus', activeMask: SIG.MEMR | SIG.MEMW },
  { from: 'io', to: 'bus', kind: 'bus', activeMask: SIG.IOR | SIG.IOW },
  { from: 'output', to: 'bus', kind: 'bus', activeMask: SIG.IOW },
  { from: 'control', to: 'pc', kind: 'ctl', activeMask: SIG.FETCH | SIG.JMP },
  { from: 'control', to: 'ram', kind: 'ctl', activeMask: SIG.MEMR | SIG.MEMW },
  { from: 'control', to: 'regs', kind: 'ctl', activeMask: SIG.ALU },
  { from: 'control', to: 'sp', kind: 'ctl', activeMask: SIG.STKR | SIG.STKW },
  { from: 'control', to: 'alu', kind: 'ctl', activeMask: SIG.ALU },
  { from: 'control', to: 'io', kind: 'ctl', activeMask: SIG.IOR | SIG.IOW },
  { from: 'control', to: 'addr', kind: 'ctl', activeMask: SIG.MEMR | SIG.MEMW | SIG.STKR | SIG.STKW },
  { from: 'clock', to: 'pc', kind: 'clk' },
  { from: 'clock', to: 'ram', kind: 'clk' },
  { from: 'clock', to: 'regs', kind: 'clk' },
  { from: 'clock', to: 'sp', kind: 'clk' },
  { from: 'clock', to: 'control', kind: 'clk' },
  { from: 'clock', to: 'io', kind: 'clk' },
  { from: 'clock', to: 'alu', kind: 'clk' },
  { from: 'control', to: 'output', kind: 'ctl', activeMask: SIG.IOW },
]

export function moduleById(id: string): ModuleDef | undefined {
  return MODULES.find((m) => m.id === id)
}

export function findChip(ref: string): { module: ModuleDef; chip: ChipDef } | undefined {
  for (const module of MODULES) {
    const chip = module.chips.find((c) => c.ref === ref)
    if (chip) return { module, chip }
  }
  return undefined
}
